language: go
before_script:
- go vet ./terraform/lambda-apigateway/...
- env GOOS=linux ARCH=amd64 go build ./terraform/lambda-apigateway/lambda/lambda.go
- zip ./lambda lambda
- cp ./lambda ./build
deploy:
  provider: s3
  access_key_id: $ACCESS_KEY_ID
  secret_access_key: $SECRET_ACCESS_KEY 
  bucket: giancarlopetrini-s3-lambda
  skip_cleanup: true
  region: us-east-1
  local_dir: build
  